
config:
  url: http://localhost
  port : 80
  apiVersion: 2.13
  user: admin
  password: cloudfoundry
  usingAppGuid: true

  parameters:
      plan-id-1-here:
        parameter1 : 1
        parameter2 : foo
      plan-id-2-here:
        parameter1 : 2
        parameter2 : bar

  services:
    -
      id: service-id-here
      plans:
        -
          id: plan-id-here
          bindable: true
      bindable: true