
checker:
  url: https://example-dev.cf.dev.eu-de-central.msh.host
  port: 80
  apiVersion: 2.13
  user: admin
  password: cloudfoundry
  authentication: basic
  provision:
    plans: //TODO config welche genau gemacht werden müssen
